version: "3.3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "maxidom_db"
      POSTGRES_USER: "maxidom_user"
      POSTGRES_PASSWORD: "12345678"
